version: '3.8'

services:
  api:
    image: librarymanagement-api:1.0
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Server=sqlserver;Database=LibraryData;User Id=sa;Password=YourStrong@Password;TrustServerCertificate=True;
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "password@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
